# Generated by Django 4.0.2 on 2022-02-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='vaccinecount',
            field=models.IntegerField(),
        ),
    ]
