# Generated by Django 4.0.2 on 2022-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofvaccine', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('vaccinecount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=100)),
                ('vaccinedate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('vaccinename', models.CharField(max_length=100)),
            ],
        ),
    ]
