# Generated by Django 4.0.2 on 2022-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0002_alter_drives_vaccinecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
